# Generated by Django 5.2.8 on 2025-11-09 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('page_username', models.CharField(max_length=100)),
                ('page_password_encrypted', models.CharField(max_length=255)),
                ('page_logo_url', models.URLField(blank=True, null=True)),
                ('page_slogan', models.CharField(blank=True, max_length=255)),
                ('page_bio', models.TextField(blank=True)),
                ('cover_post_asset_url', models.URLField(blank=True, null=True)),
                ('cover_highlight_asset_url', models.URLField(blank=True, null=True)),
                ('monthly_post_goal', models.PositiveIntegerField(default=12)),
                ('monthly_report_text', models.TextField(blank=True)),
                ('client_user', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('filming', 'آفیش فیلمبرداری'), ('post', 'تاریخ انتشار پست')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('full_scenario_text', models.TextField(blank=True)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('goal', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='idea', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('report_text', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'week_number')},
            },
        ),
    ]
